Repository ureca-3/Ureca-3team-Backend, pull requests merged in 2024-10, with the labels that each got.

#20 [Feature/6] 콘텐츠 관련 개발
  build.gradle
  src/main/java/com/ureca/child_recommend/config/gpt/GptConfig.java
  src/main/java/com/ureca/child_recommend/config/gpt/GptWebClient.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/domain/Contents.java
  src/main/java/com/ureca/child_recommend/contents/domain/ContentsMbtiScore.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsMbtiRepository.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsRepository.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/ChatDto.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/ContentsDto.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/GptDto.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/MbtiScoreDto.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/Message.java
  src/main/java/com/ureca/child_recommend/global/exception/errorcode/CommonErrorCode.java
Labels: enhancement

#22 [Feature/7] 자녀, 유저 관련 개발 및 AWS, S3 연동
  build.gradle
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/child/application/FileService.java
  src/main/java/com/ureca/child_recommend/child/application/MbtiService.java
  src/main/java/com/ureca/child_recommend/child/domain/Child.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildMbti.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildMbtiScore.java
  src/main/java/com/ureca/child_recommend/child/domain/Enum/ChildStatus.java
  src/main/java/com/ureca/child_recommend/child/infrastructure/ChildMbtiScoreRepository.java
  src/main/java/com/ureca/child_recommend/child/infrastructure/ChildRepository.java
  src/main/java/com/ureca/child_recommend/child/presentation/ChildController.java
  src/main/java/com/ureca/child_recommend/child/presentation/MbtiController.java
  src/main/java/com/ureca/child_recommend/child/presentation/dto/ChildDto.java
  src/main/java/com/ureca/child_recommend/config/jwt/SecurityConfig.java
  src/main/java/com/ureca/child_recommend/config/oauth/dto/OauthInfo.java
  src/main/java/com/ureca/child_recommend/config/redis/RedisConfig.java
  src/main/java/com/ureca/child_recommend/config/s3/S3Config.java
  src/main/java/com/ureca/child_recommend/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/child_recommend/global/response/SuccessResponse.java
  src/main/java/com/ureca/child_recommend/relation/FeedBack.java
  src/main/java/com/ureca/child_recommend/relation/application/FeedBackService.java
  src/main/java/com/ureca/child_recommend/relation/infrastructure/FeedBackRepository.java
  src/main/java/com/ureca/child_recommend/user/application/UserService.java
  src/main/java/com/ureca/child_recommend/user/domain/User.java
  src/main/java/com/ureca/child_recommend/user/dto/UserDto.java
  src/main/java/com/ureca/child_recommend/user/infrastructure/UserRepository.java
  src/main/java/com/ureca/child_recommend/user/presentation/UserController.java
Labels: enhancement

#26 Feature/11 유저기반 추천 시스템 구현
  build.gradle
  compose.yml
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/child/domain/Child.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildMbtiScore.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildVector.java
  src/main/java/com/ureca/child_recommend/child/infrastructure/ChildRepository.java
  src/main/java/com/ureca/child_recommend/child/infrastructure/ChildVectorRepository.java
  src/main/java/com/ureca/child_recommend/child/presentation/ChildController.java
  src/main/java/com/ureca/child_recommend/child/presentation/dto/ContentsDto.java
  src/main/java/com/ureca/child_recommend/config/embedding/EmbeddingUtil.java
  src/main/java/com/ureca/child_recommend/config/jwt/LoginService.java
  src/main/java/com/ureca/child_recommend/config/jwt/util/JwtUtil.java
  src/main/java/com/ureca/child_recommend/config/redis/RedisConfig.java
  src/main/java/com/ureca/child_recommend/history/domain/History.java
  src/main/java/com/ureca/child_recommend/relation/infrastructure/FeedBackRepository.java
  src/main/java/com/ureca/child_recommend/testExample/application/TestService.java
  src/main/java/com/ureca/child_recommend/testExample/infrastructure/TestRepository.java
  src/main/java/com/ureca/child_recommend/testExample/presentation/TestController.java
  src/main/java/com/ureca/child_recommend/testExample/presentation/dto/TestDto.java
  src/main/java/com/ureca/child_recommend/user/application/UserService.java
  src/main/java/com/ureca/child_recommend/user/domain/Users.java
  src/main/java/com/ureca/child_recommend/user/infrastructure/UserRepository.java
Labels: enhancement

#31 [fix/12] CORS 설정 및 사용자 정보 조회
  src/main/java/com/ureca/child_recommend/config/jwt/SecurityConfig.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsRepository.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/user/application/UserService.java
  src/main/java/com/ureca/child_recommend/user/presentation/UserController.java
Labels: fix

#33 [Feature/9] 실시간 알림 / 실시간 콘텐츠 랭킹 조회 / 최근 좋아요한 콘텐츠 목록 조회 / 좋아요 클릭 개발
  src/main/java/com/ureca/child_recommend/child/domain/ChildMbti.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildMbtiScore.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildVector.java
  src/main/java/com/ureca/child_recommend/config/redis/RedisConfig.java
  src/main/java/com/ureca/child_recommend/config/scheduling/scheduling.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/domain/Contents.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/BookDto.java
  src/main/java/com/ureca/child_recommend/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/child_recommend/history/domain/History.java
  src/main/java/com/ureca/child_recommend/notice/application/BookService.java
  src/main/java/com/ureca/child_recommend/notice/application/SseEmitterManager.java
  src/main/java/com/ureca/child_recommend/notice/application/UserSubscriber.java
  src/main/java/com/ureca/child_recommend/notice/presentation/BookController.java
  src/main/java/com/ureca/child_recommend/notice/presentation/SseController.java
  src/main/java/com/ureca/child_recommend/notice/presentation/dto/SseEvent.java
  src/main/java/com/ureca/child_recommend/viewing/application/RankingService.java
  src/main/java/com/ureca/child_recommend/viewing/application/ViewingLikesService.java
  src/main/java/com/ureca/child_recommend/viewing/application/YesterdayRankingService.java
  src/main/java/com/ureca/child_recommend/viewing/dto/ContentLikeDto.java
  src/main/java/com/ureca/child_recommend/viewing/dto/LikeRequestDto.java
  src/main/java/com/ureca/child_recommend/viewing/infrastructure/RankingFeedBackRepository.java
  src/main/java/com/ureca/child_recommend/viewing/infrastructure/UserChildRepository.java
  src/main/java/com/ureca/child_recommend/viewing/presentation/LikeController.java
  src/main/java/com/ureca/child_recommend/viewing/presentation/RedisCheckController.java
  src/main/java/com/ureca/child_recommend/viewing/presentation/RedisCheckService.java
  src/main/java/com/ureca/child_recommend/viewing/presentation/ViewingController.java
Labels: enhancement

#38 [fix/17] 회원 권한 구분 및 로그인 개선
  src/main/java/com/ureca/child_recommend/config/jwt/SecurityConfig.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/domain/Contents.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsRepository.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/user/application/UserService.java
  src/main/java/com/ureca/child_recommend/user/presentation/UserController.java
Labels: enhancement, fix

#40 [feature/15] 도서 기반 추천 시스템 - 유저가 좋아요 누른 도서와 유사한 도서 추천 기능 추가
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/child/presentation/ChildController.java
  src/main/java/com/ureca/child_recommend/child/presentation/dto/ContentsRecommendDto.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/domain/Contents.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsRepository.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/BookDto.java
  src/main/java/com/ureca/child_recommend/relation/infrastructure/FeedBackRepository.java
  src/main/java/com/ureca/child_recommend/user/presentation/UserController.java
Labels: enhancement

#44 [refactor/20] 컨텐츠 저장 시, 임베딩 벡터값도 같이 저장
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/user/domain/Enum/UserRole.java
Labels: refactor

#46 [refactor/21] 자녀 생성후, 진단완료시 자녀의 임베딩값 저장
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/child/application/MbtiService.java
  src/main/java/com/ureca/child_recommend/child/presentation/ChildController.java
Labels: refactor

#50 [fix/18] 실시간 알림 코드 FIX
  src/main/java/com/ureca/child_recommend/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/ureca/child_recommend/config/redis/util/RedisUtil.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/notice/application/SseEmitterManager.java
  src/main/java/com/ureca/child_recommend/notice/presentation/SseController.java
  src/main/java/com/ureca/child_recommend/notice/presentation/dto/NotificationDto.java
  src/main/java/com/ureca/child_recommend/viewing/application/ViewingLikesService.java
  src/main/java/com/ureca/child_recommend/viewing/dto/ContentLikeDto.java
  src/main/java/com/ureca/child_recommend/viewing/dto/LikeRequestDto.java
  src/main/java/com/ureca/child_recommend/viewing/infrastructure/RankingFeedBackRepository.java
  src/main/java/com/ureca/child_recommend/viewing/infrastructure/UserChildRepository.java
Labels: fix

#54 [refactor/24] 불필요한 피드백엔티티 x-> 컨텐츠 엔티티 접근
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/domain/Contents.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsVectorRepository.java
  src/main/java/com/ureca/child_recommend/relation/infrastructure/FeedBackRepository.java
Labels: refactor

#56 [fix/22] 콘텐츠 관련 API 개선
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsRepository.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/ContentsDto.java
  src/main/java/com/ureca/child_recommend/user/presentation/UserController.java
Labels: bug, fix

#53 [refactor/23] RedisUtil 위한 리팩토링
  src/main/java/com/ureca/child_recommend/config/redis/util/RedisUtil.java
  src/main/java/com/ureca/child_recommend/notice/presentation/SseController.java
Labels: refactor
