Repository ureca-3/Ureca-3team-Backend, pull requests merged in 2024-11, with the labels that each got.

#60 [feature/19] S3를 활용한 컨텐츠, 자녀, 사용자 이미지 업로드 기능
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/child/application/FileService.java
  src/main/java/com/ureca/child_recommend/child/presentation/ChildController.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/domain/Contents.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/global/application/S3Service.java
  src/main/java/com/ureca/child_recommend/user/application/UserService.java
  src/main/java/com/ureca/child_recommend/user/domain/Users.java
  src/main/java/com/ureca/child_recommend/user/presentation/UserController.java
Labels: enhancement, fix

#62 [typo-fix/28] 오탈자 수정
  src/main/java/com/ureca/child_recommend/child/application/MbtiService.java
  src/main/java/com/ureca/child_recommend/config/redis/util/RedisUtil.java
  src/main/java/com/ureca/child_recommend/user/application/UserService.java
Labels: typo fix

#63 [refactor/25] 도서에 대한 피드백 기능 구현 완료
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/config/redis/RedisConfig.java
  src/main/java/com/ureca/child_recommend/config/redis/util/RedisUtil.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsRepository.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsVectorRepository.java
  src/main/java/com/ureca/child_recommend/global/exception/errorcode/CommonErrorCode.java
  src/main/java/com/ureca/child_recommend/relation/Enum/FeedBackType.java
  src/main/java/com/ureca/child_recommend/relation/application/FeedBackService.java
  src/main/java/com/ureca/child_recommend/relation/domain/Enum/FeedBackType.java
  src/main/java/com/ureca/child_recommend/relation/domain/FeedBack.java
  src/main/java/com/ureca/child_recommend/relation/infrastructure/FeedBackRepository.java
  src/main/java/com/ureca/child_recommend/relation/presentation/FeedBackController.java
  src/main/java/com/ureca/child_recommend/user/application/UserService.java
  src/main/java/com/ureca/child_recommend/viewing/application/ViewingLikesService.java
  src/main/java/com/ureca/child_recommend/viewing/infrastructure/RankingFeedBackRepository.java
Labels: enhancement

#65 [refactor/29] 도서 상세 조회시 - 좋아요 상태값 응답값에 포함
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/contents/presentation/dto/ContentsDto.java
Labels: refactor

#69 [fix/31] 재 진단시 벡터디비에 값 들어가는 것 오류 수정
  src/main/java/com/ureca/child_recommend/child/application/MbtiService.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildVector.java
  src/main/java/com/ureca/child_recommend/child/infrastructure/ChildVectorRepository.java
Labels: fix

#71 Fix/31 redis의 다양한 value 처리를 위한 설정 (json, object)
  src/main/java/com/ureca/child_recommend/child/presentation/dto/ContentsRecommendDto.java
  src/main/java/com/ureca/child_recommend/config/redis/RedisConfig.java
  src/main/java/com/ureca/child_recommend/config/redis/util/RedisUtil.java
Labels: fix

#73 [typo-fix/32] 오탈자 수정/ UserController - RequestParam 수정
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/user/presentation/UserController.java
Labels: typo fix

#74 [refacture/30] 도서 기반 추천 시스템 - 조회 시, redis를 활용한 성능 최적화
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/relation/application/FeedBackService.java
  src/main/java/com/ureca/child_recommend/relation/infrastructure/FeedBackRepository.java
Labels: refactor

#76 [feature/33] 실시간(하루) 좋아요 많이 받은 도서 추천
  src/main/java/com/ureca/child_recommend/config/redis/util/RedisUtil.java
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
  src/main/java/com/ureca/child_recommend/relation/application/FeedBackService.java
Labels: enhancement

#77 [feature/33] 실시간(하루) 좋아요 많이 받은 도서 추천 - 앞에 pr에 누락
  src/main/java/com/ureca/child_recommend/relation/application/FeedBackSchedulerService.java
Labels: enhancement

#79 [feature/34] mbti타입에 따른 컨텐츠 조회 구현
  src/main/java/com/ureca/child_recommend/contents/application/ContentsService.java
  src/main/java/com/ureca/child_recommend/contents/infrastructure/ContentsRepository.java
  src/main/java/com/ureca/child_recommend/contents/presentation/ContentsController.java
Labels: enhancement

#81 [feature/35] 해당 컨텐츠 좋아요 시, 컨텐츠의 mbti 성향에 따른 해당 자녀의 mbti 성향 변화
  src/main/java/com/ureca/child_recommend/child/application/ChildService.java
  src/main/java/com/ureca/child_recommend/child/application/MbtiService.java
  src/main/java/com/ureca/child_recommend/child/domain/Child.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildMbti.java
  src/main/java/com/ureca/child_recommend/child/domain/ChildMbtiScore.java
  src/main/java/com/ureca/child_recommend/relation/application/FeedBackService.java
Labels: enhancement
